# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'


target 'DNSServer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DNSServer
#  pod 'SwiftSocket'
#pod 'CocoaAsyncSocket'

end
